
server:
  port: 8080
  context-path:
  tomcat:
    uri-encoding: UTF-8


logging:
  config: classpath:logback.xml


mybatis:
  # mybatis配置文件所在路径
  mapper-locations: classpath:com.exam.manage.persistence/**/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.exam.common.domain
spring:


  datasource:
    url: jdbc:mysql://localhost:3306/hopeExam?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver



  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp